## Demo playbook for creating Linux (Redhat) EC2 Instance.
# 1) Spins up a new EC2 Instance
# 2) Collects new instance's variables
# 3) Waits for SSH to become active on new Instance
- hosts: localhost
#  vars:
  tasks:
    - name: Provision a new EC2 instance
      ec2:
        aws_access_key:
        aws_secret_key:
        key_name: MyMumbaiKeyPair
        region: ap-south-1
        instance_type: t2.micro
        image: ami-5b673c34
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: My2ndAutomaticEC2
          Owner: Gaurav
        monitoring: no
        vpc_subnet_id: subnet-66aaea0e
        assign_public_ip: yes
        group: MyDMZ
      register: ec2_out

    - name: Print all ec2 variables
      debug: var=ec2

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=360 state=started
      with_items: '{{ec2_out.instances}}'
