---
# This is the playbook for installing, starting up the ntp client on list of hosts.

- hosts: all
  become: yes
  become_user: root
  become_method: su
#  ansible_become_pass: redhat
  vars:
    ntp_server: 192.168.122.1
  tasks:
    # This task is to ensure chrony package is not installed. Having both chrony and ntp package installed can cause conflict on the machine.
  - name: remove chrony package from the client machine
    yum:
      name=chrony
      state=absent
    tags: remove_chrony, start_ntp
    # This task is to ensure the ntp package is installed.
  - name: install ntp package on client machine
    yum:
      name: ntp
      state: present
    tags: install_ntp, start_ntp
    # This task is to copy custom ntp.conf file
  - name: deploy ntp.conf file to client
    template:
        src=/etc/ansible/templates/ntp.j2
        dest=/etc/ntp.conf
        owner=root
        group=root
        mode=0644
        backup=yes
    notify: start_restart_ntp_client
    tags: copy_ntp_conf, start_ntp

  handlers:
    # This task is to start the ntp client
  - name: start_restart_ntp_client
    service: name=ntpd state=restarted enabled=yes
